(function (define) {
  define(['jquery'], function ($) {
    return (function () {
      var adto = window.adto || {};

      /* Application paths *****************************************/

      //Version
      adto.aspnetboilerplate = adto.aspnetboilerplate || {};
      adto.aspnetboilerplate.version = '8.0.0';
      
      //Current application root path (including virtual directory if exists).
      adto.appPath = adto.appPath || '/';
      adto.pageLoadTime = new Date();

      //Converts given path to absolute path using adto.appPath variable.
      adto.toAbsAppPath = function (path) {
        if (path.indexOf('/') == 0) {
          path = path.substring(1);
        }

        return adto.appPath + path;
      };

      /* MULTITENANCY */

      adto.multiTenancy = adto.multiTenancy || {};

    adto.multiTenancy.isEnabled = false;
    adto.multiTenancy.ignoreFeatureCheckForHostUsers = false;

      adto.multiTenancy.sides = {
        TENANT: 1,
        HOST: 2
      };

      adto.multiTenancy.tenantIdCookieName = 'ADTOSharp-TenantId';

      adto.multiTenancy.setTenantIdCookie = function (tenantId) {
        if (tenantId) {
          adto.utils.setCookieValue(
            adto.multiTenancy.tenantIdCookieName,
            tenantId.toString(),
            new Date(new Date().getTime() + 5 * 365 * 86400000), //5 years
            adto.appPath,
            adto.domain
          );
        } else {
          adto.utils.deleteCookie(adto.multiTenancy.tenantIdCookieName, adto.appPath);
        }
      };

      adto.multiTenancy.getTenantIdCookie = function () {
        var value = adto.utils.getCookieValue(adto.multiTenancy.tenantIdCookieName);
        if (!value) {
          return null;
        }

        return parseInt(value);
      }

      /* SESSION */

      adto.session = adto.session ||
        {
          multiTenancySide: adto.multiTenancy.sides.HOST
        };

      /* LOCALIZATION ***********************************************/
      //Implements Localization API that simplifies usage of localization scripts generated by ADTOSharp.

      adto.localization = adto.localization || {};

      adto.localization.languages = [];

      adto.localization.currentLanguage = {};

      adto.localization.sources = [];

      adto.localization.values = {};

      adto.localization.localize = function (key, sourceName) {
        sourceName = sourceName || adto.localization.defaultSourceName;

        var source = adto.localization.values[sourceName];

        if (!source) {
          adto.log.warn('Could not find localization source: ' + sourceName);
          return key;
        }

        var value = source[key];
        if (value == undefined) {
          return key;
        }

        var copiedArguments = Array.prototype.slice.call(arguments, 0);
        copiedArguments.splice(1, 1);
        copiedArguments[0] = value;

        return adto.utils.formatString.apply(this, copiedArguments);
      };

      adto.localization.getSource = function (sourceName) {
        return function (key) {
          var copiedArguments = Array.prototype.slice.call(arguments, 0);
          copiedArguments.splice(1, 0, sourceName);
          return adto.localization.localize.apply(this, copiedArguments);
        };
      };

      adto.localization.isCurrentCulture = function (name) {
        return adto.localization.currentCulture
          && adto.localization.currentCulture.name
          && adto.localization.currentCulture.name.indexOf(name) == 0;
      };

      adto.localization.defaultSourceName = undefined;
      adto.localization.adtoWeb = adto.localization.getSource('ADTOSharpWeb');

      /* AUTHORIZATION **********************************************/
      //Implements Authorization API that simplifies usage of authorization scripts generated by ADTOSharp.

      adto.auth = adto.auth || {};

      adto.auth.allPermissions = adto.auth.allPermissions || {};

      adto.auth.grantedPermissions = adto.auth.grantedPermissions || {};

      //Deprecated. Use adto.auth.isGranted instead.
      adto.auth.hasPermission = function (permissionName) {
        return adto.auth.isGranted.apply(this, arguments);
      };

      //Deprecated. Use adto.auth.isAnyGranted instead.
      adto.auth.hasAnyOfPermissions = function () {
        return adto.auth.isAnyGranted.apply(this, arguments);
      };

      //Deprecated. Use adto.auth.areAllGranted instead.
      adto.auth.hasAllOfPermissions = function () {
        return adto.auth.areAllGranted.apply(this, arguments);
      };

      adto.auth.isGranted = function (permissionName) {
        return adto.auth.grantedPermissions[permissionName] != undefined;
      };

      adto.auth.isAnyGranted = function () {
        if (!arguments || arguments.length <= 0) {
          return true;
        }

        for (var i = 0; i < arguments.length; i++) {
          if (adto.auth.isGranted(arguments[i])) {
            return true;
          }
        }

        return false;
      };

      adto.auth.areAllGranted = function () {
        if (!arguments || arguments.length <= 0) {
          return true;
        }

        for (var i = 0; i < arguments.length; i++) {
          if (!adto.auth.isGranted(arguments[i])) {
            return false;
          }
        }

        return true;
      };

      adto.auth.tokenCookieName = 'ADTOSharp.AuthToken';

      adto.auth.setToken = function (authToken, expireDate) {
        adto.utils.setCookieValue(adto.auth.tokenCookieName, authToken, expireDate, adto.appPath, adto.domain);
      };

      adto.auth.getToken = function() {
          return adto.utils.getCookieValue(adto.auth.tokenCookieName);
      };

      adto.auth.clearToken = function() {
          adto.auth.setToken();
      };

      adto.auth.refreshTokenCookieName = 'ADTOSharp.AuthRefreshToken';

      adto.auth.setRefreshToken = function (refreshToken, expireDate) {
          adto.utils.setCookieValue(adto.auth.refreshTokenCookieName, refreshToken, expireDate, adto.appPath, adto.domain);
      };

      adto.auth.getRefreshToken = function() {
          return adto.utils.getCookieValue(adto.auth.refreshTokenCookieName);
      };

      adto.auth.clearRefreshToken = function() {
          adto.auth.setRefreshToken();
      };

      /* FEATURE SYSTEM *********************************************/
      //Implements Features API that simplifies usage of feature scripts generated by ADTOSharp.

      adto.features = adto.features || {};

      adto.features.allFeatures = adto.features.allFeatures || {};

      adto.features.get = function (name) {
        return adto.features.allFeatures[name];
      }

      adto.features.getValue = function (name) {
        var feature = adto.features.get(name);
        if (feature == undefined) {
          return undefined;
        }

        return feature.value;
      }

      adto.features.isEnabled = function (name) {
        var value = adto.features.getValue(name);
        return value == 'true' || value == 'True';
      }

      /* SETTINGS **************************************************/
      //Implements Settings API that simplifies usage of setting scripts generated by ADTOSharp.

      adto.setting = adto.setting || {};

      adto.setting.values = adto.setting.values || {};

      adto.setting.get = function (name) {
        return adto.setting.values[name];
      };

      adto.setting.getBoolean = function (name) {
        var value = adto.setting.get(name);
        return value == 'true' || value == 'True';
      };

      adto.setting.getInt = function (name) {
        return parseInt(adto.setting.values[name]);
      };

      /* REALTIME NOTIFICATIONS ************************************/

      adto.notifications = adto.notifications || {};

      adto.notifications.severity = {
        INFO: 0,
        SUCCESS: 1,
        WARN: 2,
        ERROR: 3,
        FATAL: 4
      };

      adto.notifications.userNotificationState = {
        UNREAD: 0,
        READ: 1
      };

      adto.notifications.getUserNotificationStateAsString = function (userNotificationState) {
        switch (userNotificationState) {
          case adto.notifications.userNotificationState.READ:
            return 'READ';
          case adto.notifications.userNotificationState.UNREAD:
            return 'UNREAD';
          default:
            adto.log.warn('Unknown user notification state value: ' + userNotificationState)
            return '?';
        }
      };

      adto.notifications.getUiNotifyFuncBySeverity = function (severity) {
        switch (severity) {
          case adto.notifications.severity.SUCCESS:
            return adto.notify.success;
          case adto.notifications.severity.WARN:
            return adto.notify.warn;
          case adto.notifications.severity.ERROR:
            return adto.notify.error;
          case adto.notifications.severity.FATAL:
            return adto.notify.error;
          case adto.notifications.severity.INFO:
          default:
            return adto.notify.info;
        }
      };

      adto.notifications.messageFormatters = {};

      adto.notifications.messageFormatters['ADTOSharp.Notifications.MessageNotificationData'] = function (userNotification) {
        return userNotification.notification.data.message || userNotification.notification.data.properties.Message;
      };

      adto.notifications.messageFormatters['ADTOSharp.Notifications.LocalizableMessageNotificationData'] =
        function (userNotification) {
          var message = userNotification.notification.data.message ||
            userNotification.notification.data.properties.Message;
          var localizedMessage = adto.localization.localize(
            message.name,
            message.sourceName
          );

          if (userNotification.notification.data.properties) {
            if ($) {
              //Prefer to use jQuery if possible
              $.each(userNotification.notification.data.properties, function (key, value) {
                localizedMessage = localizedMessage.replace('{' + key + '}', value);
              });
            } else {
              //alternative for $.each
              var properties = Object.keys(userNotification.notification.data.properties);
              for (var i = 0; i < properties.length; i++) {
                localizedMessage = localizedMessage.replace('{' + properties[i] + '}',
                  userNotification.notification.data.properties[properties[i]]);
              }
            }
          }

          return localizedMessage;
        };

      adto.notifications.getFormattedMessageFromUserNotification = function (userNotification) {
        var formatter = adto.notifications.messageFormatters[userNotification.notification.data.type];
        if (!formatter) {
          adto.log.warn('No message formatter defined for given data type: ' + userNotification.notification.data.type)
          return '?';
        }

        if (!adto.utils.isFunction(formatter)) {
          adto.log.warn('Message formatter should be a function! It is invalid for data type: ' +
            userNotification.notification.data.type)
          return '?';
        }

        return formatter(userNotification);
      }

      adto.notifications.showUiNotifyForUserNotification = function (userNotification, options) {
        var message = adto.notifications.getFormattedMessageFromUserNotification(userNotification);
        var uiNotifyFunc = adto.notifications.getUiNotifyFuncBySeverity(userNotification.notification.severity);
        uiNotifyFunc(message, undefined, options);
      }

      /* LOGGING ***************************************************/
      //Implements Logging API that provides secure & controlled usage of console.log

      adto.log = adto.log || {};

      adto.log.levels = {
        DEBUG: 1,
        INFO: 2,
        WARN: 3,
        ERROR: 4,
        FATAL: 5
      };

      adto.log.level = adto.log.levels.DEBUG;

      adto.log.log = function (logObject, logLevel) {
        if (!window.console || !window.console.log) {
          return;
        }

        if (logLevel != undefined && logLevel < adto.log.level) {
          return;
        }

        console.log(logObject);
      };

      adto.log.debug = function (logObject) {
        adto.log.log("DEBUG: ", adto.log.levels.DEBUG);
        adto.log.log(logObject, adto.log.levels.DEBUG);
      };

      adto.log.info = function (logObject) {
        adto.log.log("INFO: ", adto.log.levels.INFO);
        adto.log.log(logObject, adto.log.levels.INFO);
      };

      adto.log.warn = function (logObject) {
        adto.log.log("WARN: ", adto.log.levels.WARN);
        adto.log.log(logObject, adto.log.levels.WARN);
      };

      adto.log.error = function (logObject) {
        adto.log.log("ERROR: ", adto.log.levels.ERROR);
        adto.log.log(logObject, adto.log.levels.ERROR);
      };

      adto.log.fatal = function (logObject) {
        adto.log.log("FATAL: ", adto.log.levels.FATAL);
        adto.log.log(logObject, adto.log.levels.FATAL);
      };

      /* NOTIFICATION *********************************************/
      //Defines Notification API, not implements it

      adto.notify = adto.notify || {};

      adto.notify.success = function (message, title, options) {
        adto.log.warn('adto.notify.success is not implemented!');
      };

      adto.notify.info = function (message, title, options) {
        adto.log.warn('adto.notify.info is not implemented!');
      };

      adto.notify.warn = function (message, title, options) {
        adto.log.warn('adto.notify.warn is not implemented!');
      };

      adto.notify.error = function (message, title, options) {
        adto.log.warn('adto.notify.error is not implemented!');
      };

      /* MESSAGE **************************************************/
      //Defines Message API, not implements it

      adto.message = adto.message || {};

    var showMessage = function (message, title, options) {
        alert((title || '') + ' ' + message);

        if (!$) {
          adto.log.warn('adto.message can not return promise since jQuery is not defined!');
          return null;
        }

        return $.Deferred(function ($dfd) {
          $dfd.resolve();
        });
      };

    adto.message.info = function (message, title, options) {
        adto.log.warn('adto.message.info is not implemented!');
        return showMessage(message, title, options);
    };

    adto.message.success = function (message, title, options) {
        adto.log.warn('adto.message.success is not implemented!');
        return showMessage(message, title, options);
    };

    adto.message.warn = function (message, title, options) {
        adto.log.warn('adto.message.warn is not implemented!');
        return showMessage(message, title, options);
    };

    adto.message.error = function (message, title, options) {
        adto.log.warn('adto.message.error is not implemented!');
        return showMessage(message, title, options);
    };

    adto.message.confirm = function (message, title, callback, options) {
        adto.log.warn('adto.message.confirm is not implemented!');

        var result = confirm(message);
        callback && callback(result);

        if (!$) {
          adto.log.warn('adto.message can not return promise since jQuery is not defined!');
          return null;
        }

        return $.Deferred(function ($dfd) {
          $dfd.resolve();
        });
      };

      /* UI *******************************************************/

      adto.ui = adto.ui || {};

      /* UI BLOCK */
      //Defines UI Block API, not implements it

      adto.ui.block = function (elm) {
        adto.log.warn('adto.ui.block is not implemented!');
      };

      adto.ui.unblock = function (elm) {
        adto.log.warn('adto.ui.unblock is not implemented!');
      };

      /* UI BUSY */
      //Defines UI Busy API, not implements it

      adto.ui.setBusy = function (elm, optionsOrPromise) {
        adto.log.warn('adto.ui.setBusy is not implemented!');
      };

      adto.ui.clearBusy = function (elm) {
        adto.log.warn('adto.ui.clearBusy is not implemented!');
      };

      /* SIMPLE EVENT BUS *****************************************/

      adto.event = (function () {

        var _callbacks = {};

        var on = function (eventName, callback) {
          if (!_callbacks[eventName]) {
            _callbacks[eventName] = [];
          }

          _callbacks[eventName].push(callback);
        };

        var off = function (eventName, callback) {
          var callbacks = _callbacks[eventName];
          if (!callbacks) {
            return;
          }

          var index = -1;
          for (var i = 0; i < callbacks.length; i++) {
            if (callbacks[i] === callback) {
              index = i;
              break;
            }
          }

          if (index < 0) {
            return;
          }

          _callbacks[eventName].splice(index, 1);
        };

        var trigger = function (eventName) {
          var callbacks = _callbacks[eventName];
          if (!callbacks || !callbacks.length) {
            return;
          }

          var args = Array.prototype.slice.call(arguments, 1);
          for (var i = 0; i < callbacks.length; i++) {
            callbacks[i].apply(this, args);
          }
        };

        // Public interface ///////////////////////////////////////////////////

        return {
          on: on,
          off: off,
          trigger: trigger
        };
      })();

      /* UTILS ***************************************************/

      adto.utils = adto.utils || {};

      /* Creates a name namespace.
      *  Example:
      *  var taskService = adto.utils.createNamespace(adto, 'services.task');
      *  taskService will be equal to adto.services.task
      *  first argument (root) must be defined first
      ************************************************************/
      adto.utils.createNamespace = function (root, ns) {
        var parts = ns.split('.');
        for (var i = 0; i < parts.length; i++) {
          if (typeof root[parts[i]] == 'undefined') {
            root[parts[i]] = {};
          }

          root = root[parts[i]];
        }

        return root;
      };

      /* Find and replaces a string (search) to another string (replacement) in
      *  given string (str).
      *  Example:
      *  adto.utils.replaceAll('This is a test string', 'is', 'X') = 'ThX X a test string'
      ************************************************************/
      adto.utils.replaceAll = function (str, search, replacement) {
        var fix = search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        return str.replace(new RegExp(fix, 'g'), replacement);
      };

      /* Formats a string just like string.format in C#.
      *  Example:
      *  adto.utils.formatString('Hello {0}','Tuana') = 'Hello Tuana'
      ************************************************************/
      adto.utils.formatString = function () {
        if (arguments.length < 1) {
          return null;
        }

        var str = arguments[0];

        for (var i = 1; i < arguments.length; i++) {
          var placeHolder = '{' + (i - 1) + '}';
          str = adto.utils.replaceAll(str, placeHolder, arguments[i]);
        }

        return str;
      };

      adto.utils.toPascalCase = function (str) {
        if (!str || !str.length) {
          return str;
        }

        if (str.length === 1) {
          return str.charAt(0).toUpperCase();
        }

        return str.charAt(0).toUpperCase() + str.substr(1);
      }

      adto.utils.toCamelCase = function (str) {
        if (!str || !str.length) {
          return str;
        }

        if (str.length === 1) {
          return str.charAt(0).toLowerCase();
        }

        return str.charAt(0).toLowerCase() + str.substr(1);
      }

      adto.utils.truncateString = function (str, maxLength) {
        if (!str || !str.length || str.length <= maxLength) {
          return str;
        }

        return str.substr(0, maxLength);
      };

      adto.utils.truncateStringWithPostfix = function (str, maxLength, postfix) {
        postfix = postfix || '...';

        if (!str || !str.length || str.length <= maxLength) {
          return str;
        }

        if (maxLength <= postfix.length) {
          return postfix.substr(0, maxLength);
        }

        return str.substr(0, maxLength - postfix.length) + postfix;
      };

      adto.utils.ensureEndsWith = function (str, c) {
        if (!str) {
          return str;
        }

        if (str.endsWith(c))
        {
          return str;
        }

        return str + c;
      };      

      adto.utils.isFunction = function (obj) {
        if ($) {
          //Prefer to use jQuery if possible
          return $.isFunction(obj);
        }

        //alternative for $.isFunction
        return !!(obj && obj.constructor && obj.call && obj.apply);
      };

      /**
       * parameterInfos should be an array of { name, value } objects
       * where name is query string parameter name and value is it's value.
       * includeQuestionMark is true by default.
       */
      adto.utils.buildQueryString = function (parameterInfos, includeQuestionMark) {
        if (includeQuestionMark === undefined) {
          includeQuestionMark = true;
        }

        var qs = '';

        function addSeperator() {
          if (!qs.length) {
            if (includeQuestionMark) {
              qs = qs + '?';
            }
          } else {
            qs = qs + '&';
          }
        }

        for (var i = 0; i < parameterInfos.length; ++i) {
          var parameterInfo = parameterInfos[i];
          if (parameterInfo.value === undefined) {
            continue;
          }

          if (parameterInfo.value === null) {
            parameterInfo.value = '';
          }

          addSeperator();

          if (parameterInfo.value.toJSON && typeof parameterInfo.value.toJSON === "function") {
            qs = qs + parameterInfo.name + '=' + encodeURIComponent(parameterInfo.value.toJSON());
          } else if (Array.isArray(parameterInfo.value) && parameterInfo.value.length) {
            for (var j = 0; j < parameterInfo.value.length; j++) {
              if (j > 0) {
                addSeperator();
              }

              qs = qs + parameterInfo.name + '[' + j + ']=' + encodeURIComponent(parameterInfo.value[j]);
            }
          } else {
            qs = qs + parameterInfo.name + '=' + encodeURIComponent(parameterInfo.value);
          }
        }

        return qs;
      }

      /**
       * Sets a cookie value for given key.
       * This is a simple implementation created to be used by ADTO.
       * Please use a complete cookie library if you need.
       * @param {string} key
       * @param {string} value 
       * @param {Date} expireDate (optional). If not specified the cookie will expire at the end of session.
       * @param {string} path (optional)
       * @param {string} domain (optional)
       * @param {any} attributes (optional)
       */
      adto.utils.setCookieValue = function (key, value, expireDate, path, domain, attributes) {
        var cookieValue = encodeURIComponent(key) + '=';

        if (value) {
          cookieValue = cookieValue + encodeURIComponent(value);
        }

        if (expireDate) {
          cookieValue = cookieValue + "; expires=" + expireDate.toUTCString();
        }

        if (path) {
          cookieValue = cookieValue + "; path=" + path;
        }

        if (domain) {
          cookieValue = cookieValue + "; domain=" + domain;
        }

        for (var name in attributes) {
          if (!attributes[name]) {
            continue;
          }

          cookieValue += '; ' + name;
          if (attributes[name] === true) {
            continue;
          }

          cookieValue += '=' + attributes[name].split(';')[0];
        }

        document.cookie = cookieValue;
      };

      /**
       * Gets a cookie with given key.
       * This is a simple implementation created to be used by ADTO.
       * Please use a complete cookie library if you need.
       * @param {string} key
       * @returns {string} Cookie value or null
       */
      adto.utils.getCookieValue = function (key) {
        var equalities = document.cookie.split('; ');
        for (var i = 0; i < equalities.length; i++) {
          if (!equalities[i]) {
            continue;
          }

          var splitted = equalities[i].split('=');
          if (splitted.length != 2) {
            continue;
          }

          if (decodeURIComponent(splitted[0]) === key) {
            return decodeURIComponent(splitted[1] || '');
          }
        }

        return null;
      };

      /**
       * Deletes cookie for given key.
       * This is a simple implementation created to be used by ADTO.
       * Please use a complete cookie library if you need.
       * @param {string} key
       * @param {string} path (optional)
       */
      adto.utils.deleteCookie = function (key, path) {
        var cookieValue = encodeURIComponent(key) + '=';

        cookieValue = cookieValue + "; expires=" + (new Date(new Date().getTime() - 86400000)).toUTCString();

        if (path) {
          cookieValue = cookieValue + "; path=" + path;
        }

        document.cookie = cookieValue;
      }

      /**
       * Gets the domain of given url
       * @param {string} url 
       * @returns {string} 
       */
      adto.utils.getDomain = function (url) {
        var domainRegex = /(https?:){0,1}\/\/((?:[\w\d-]+\.)+[\w\d]{2,})/i;
        var matches = domainRegex.exec(url);
        return (matches && matches[2]) ? matches[2] : '';
      }

      /* TIMING *****************************************/
      adto.timing = adto.timing || {};

      adto.timing.utcClockProvider = (function () {

        var toUtc = function (date) {
          return Date.UTC(
            date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), date.getUTCHours(), date.getUTCMinutes(),
            date.getUTCSeconds(), date.getUTCMilliseconds()
          );
        }

        var now = function () {
          return toUtc(new Date());
        };

        var normalize = function (date) {
          if (!date) {
            return date;
          }

          return new Date(toUtc(date));
        };

        // Public interface ///////////////////////////////////////////////////

        return {
          now: now,
          normalize: normalize,
          supportsMultipleTimezone: true
        };
      })();

      adto.timing.localClockProvider = (function () {

        var toLocal = function (date) {
          return new Date(
            date.getFullYear(), date.getMonth(), date.getDate(), date.getHours(), date.getMinutes(), date.getSeconds(),
            date.getMilliseconds()
          );
        }

        var now = function () {
          return toLocal(new Date());
        }

        var normalize = function (date) {
          if (!date) {
            return date;
          }

          return toLocal(date);
        }

        // Public interface ///////////////////////////////////////////////////

        return {
          now: now,
          normalize: normalize,
          supportsMultipleTimezone: false
        };
      })();

      adto.timing.unspecifiedClockProvider = (function () {

        var now = function () {
          return new Date();
        }

        var normalize = function (date) {
          return date;
        }

        // Public interface ///////////////////////////////////////////////////

        return {
          now: now,
          normalize: normalize,
          supportsMultipleTimezone: false
        };
      })();

      adto.timing.convertToUserTimezone = function (date) {
        var localTime = date.getTime();
        var utcTime = localTime + (date.getTimezoneOffset() * 60000);
        var targetTime = parseInt(utcTime) + parseInt(adto.timing.timeZoneInfo.windows.currentUtcOffsetInMilliseconds);
        return new Date(targetTime);
      };

      /* CLOCK *****************************************/
      adto.clock = adto.clock || {};

      adto.clock.now = function () {
        if (adto.clock.provider) {
          return adto.clock.provider.now();
        }

        return new Date();
      }

      adto.clock.normalize = function (date) {
        if (adto.clock.provider) {
          return adto.clock.provider.normalize(date);
        }

        return date;
      }

      adto.clock.provider = adto.timing.unspecifiedClockProvider;

      /* SECURITY ***************************************/
      adto.security = adto.security || {};
      adto.security.antiForgery = adto.security.antiForgery || {};

      adto.security.antiForgery.tokenCookieName = 'XSRF-TOKEN';
      adto.security.antiForgery.tokenHeaderName = 'X-XSRF-TOKEN';

      adto.security.antiForgery.getToken = function () {
        return adto.utils.getCookieValue(adto.security.antiForgery.tokenCookieName);
      };

      adto.security.antiForgery.shouldSendToken = function (settings) {
        if (settings.crossDomain === undefined || settings.crossDomain === null) {
          return adto.utils.getDomain(location.href) === adto.utils.getDomain(settings.url);
        }

        return !settings.crossDomain;
      };

      return adto;
    })();
  });
}(typeof define === 'function' && define.amd
  ? define
  : function (deps, factory) {
    if (typeof module !== 'undefined' && module.exports) {
      module.exports = factory(require('jquery'));
    } else {
      window.adto = factory(window.jQuery);
    }
  }));
